"""
MQL5 Expert Advisor code generator.

Converts an AlgoForge strategy dict into a fully compilable MQL5 .mq5 source file.
"""
from __future__ import annotations

import textwrap
from typing import Any


# ──────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────

def generate_ea(strategy: dict) -> str:
    """
    Generate a complete, compilable MQL5 Expert Advisor source file.

    Args:
        strategy: Strategy dict as returned by the strategy service.

    Returns:
        A string containing the full .mq5 source code.
    """
    name = strategy.get("name", "AlgoForge_EA")
    description = strategy.get("description") or f"Generated by AlgoForge — {name}"
    instrument = strategy.get("instrument", "EURUSD")
    timeframe = strategy.get("timeframe", "H1")
    direction = strategy.get("direction", "BOTH")
    risk_per_trade = strategy.get("risk_per_trade", 1.0)
    max_daily_drawdown = strategy.get("max_daily_drawdown", 5.0)
    session_filter = strategy.get("session_filter", [])
    entry_conditions: list[dict] = strategy.get("entry_conditions", [])
    exit_conditions: list[dict] = strategy.get("exit_conditions", [])

    # Collect all unique indicators referenced in conditions
    all_conditions = entry_conditions + exit_conditions
    indicators = _collect_indicators(all_conditions)

    # Build source sections
    header = _build_header(name, description)
    includes = _build_includes()
    inputs = _build_inputs(instrument, timeframe, risk_per_trade, max_daily_drawdown, indicators, session_filter)
    globals_ = _build_globals(indicators)
    on_init = _build_on_init(indicators)
    on_deinit = _build_on_deinit(indicators)
    on_tick = _build_on_tick(direction, entry_conditions, exit_conditions, indicators, session_filter)
    helpers = _build_helpers()

    return "\n".join([
        header,
        includes,
        inputs,
        globals_,
        on_init,
        on_deinit,
        on_tick,
        helpers,
    ])


# ──────────────────────────────────────────────
# Section builders
# ──────────────────────────────────────────────

def _build_header(name: str, description: str) -> str:
    safe_name = name.replace('"', '\\"')
    safe_desc = description.replace('"', '\\"')
    return textwrap.dedent(f"""\
        //+------------------------------------------------------------------+
        //|  {safe_name}.mq5                                                  |
        //|  {safe_desc}                                                      |
        //|  Generated by AlgoForge                                           |
        //+------------------------------------------------------------------+
        #property copyright   "AlgoForge"
        #property link        "https://algoforge.io"
        #property version     "1.00"
        #property description "{safe_desc}"
        #property strict
    """)


def _build_includes() -> str:
    return textwrap.dedent("""\
        #include <Trade\\Trade.mqh>
        #include <Trade\\SymbolInfo.mqh>
    """)


def _build_inputs(
    instrument: str,
    timeframe: str,
    risk_per_trade: float,
    max_daily_drawdown: float,
    indicators: list[dict],
    session_filter: list,
) -> str:
    lines = ["//--- Input parameters"]
    lines.append(f'input string   InpSymbol          = "{instrument}";      // Trading Symbol')
    lines.append(f'input ENUM_TIMEFRAMES InpTimeframe = {_tf_to_mql5(timeframe)};  // Timeframe')
    lines.append(f"input double   InpRiskPerTrade     = {risk_per_trade};          // Risk Per Trade (%)")
    lines.append(f"input double   InpMaxDailyDrawdown = {max_daily_drawdown};          // Max Daily Drawdown (%)")
    lines.append(f'input string   InpSessions        = "{_sessions_to_string(session_filter)}"; // Trading Sessions (e.g. "London,NewYork")')
    lines.append("input double   InpSlippage         = 3;              // Slippage (points)")
    lines.append("input double   InpStopLossATRMult  = 1.5;            // ATR SL Multiplier")
    lines.append("input double   InpTakeProfitATRMult= 3.0;            // ATR TP Multiplier")
    lines.append("")

    # Indicator-specific inputs
    for ind in indicators:
        ind_name = ind["name"].upper()
        params = ind.get("params", {})
        prefix = ind["input_prefix"]

        if ind_name == "RSI":
            lines.append(f'input int      {prefix}Period     = {params.get("period", 14)};  // RSI Period')
            lines.append(f'input int      {prefix}OverboughtLevel = 70; // RSI Overbought Level')
            lines.append(f'input int      {prefix}OversoldLevel   = 30; // RSI Oversold Level')
        elif ind_name == "MACD":
            lines.append(f'input int      {prefix}FastEMA    = {params.get("fast", 12)};  // MACD Fast EMA')
            lines.append(f'input int      {prefix}SlowEMA    = {params.get("slow", 26)};  // MACD Slow EMA')
            lines.append(f'input int      {prefix}Signal     = {params.get("signal", 9)};   // MACD Signal Period')
        elif ind_name == "EMA":
            lines.append(f'input int      {prefix}Period     = {params.get("period", 20)};  // EMA Period')
        elif ind_name == "SMA":
            lines.append(f'input int      {prefix}Period     = {params.get("period", 50)};  // SMA Period')
        elif ind_name in ("BOLLINGER", "BB"):
            lines.append(f'input int      {prefix}Period     = {params.get("period", 20)};  // Bollinger Bands Period')
            lines.append(f'input double   {prefix}StdDev     = {params.get("std_dev", 2.0)};   // Bollinger Bands Std Dev')
        elif ind_name == "ATR":
            lines.append(f'input int      {prefix}Period     = {params.get("period", 14)};  // ATR Period')
        elif ind_name == "STOCHASTIC":
            lines.append(f'input int      {prefix}KPeriod    = {params.get("k_period", 14)};  // Stochastic K Period')
            lines.append(f'input int      {prefix}DPeriod    = {params.get("d_period", 3)};   // Stochastic D Period')
            lines.append(f'input int      {prefix}Slowing    = 3;  // Stochastic Slowing')
        elif ind_name == "CCI":
            lines.append(f'input int      {prefix}Period     = {params.get("period", 20)};  // CCI Period')

    return "\n".join(lines) + "\n"


def _build_globals(indicators: list[dict]) -> str:
    lines = ["//--- Global variables", "CTrade   g_trade;", "int      g_magic = 20240101;", ""]

    # Indicator handle declarations
    for ind in indicators:
        handle_name = ind["handle_var"]
        lines.append(f"int      {handle_name} = INVALID_HANDLE;")

    lines += [
        "",
        "// Position tracking",
        "bool     g_position_open = false;",
        "double   g_entry_price   = 0.0;",
        "double   g_stop_loss     = 0.0;",
        "double   g_take_profit   = 0.0;",
        "int      g_position_dir  = 0;   // 1=LONG, -1=SHORT",
        "double   g_daily_start_balance = 0.0;",
        "",
        "// Buffer arrays",
    ]

    for ind in indicators:
        buf_names = ind.get("buffer_vars", [])
        for buf in buf_names:
            lines.append(f"double   {buf}[];")

    return "\n".join(lines) + "\n"


def _build_on_init(indicators: list[dict]) -> str:
    lines = [
        "//+------------------------------------------------------------------+",
        "int OnInit()",
        "{",
        "   g_trade.SetExpertMagicNumber(g_magic);",
        "   g_trade.SetDeviationInPoints((ulong)InpSlippage);",
        "   g_daily_start_balance = AccountInfoDouble(ACCOUNT_BALANCE);",
        "",
    ]

    for ind in indicators:
        ind_name = ind["name"].upper()
        handle_var = ind["handle_var"]
        prefix = ind["input_prefix"]
        params = ind.get("params", {})

        init_call = _indicator_init_call(ind_name, handle_var, prefix, params)
        lines += init_call

    lines += [
        "",
        "   // Set buffer arrays as series",
    ]

    for ind in indicators:
        for buf in ind.get("buffer_vars", []):
            lines.append(f"   ArraySetAsSeries({buf}, true);")

    lines += [
        "",
        "   return(INIT_SUCCEEDED);",
        "}",
        "",
    ]
    return "\n".join(lines)


def _indicator_init_call(ind_name: str, handle_var: str, prefix: str, params: dict) -> list[str]:
    """Return lines of MQL5 code to create an indicator handle."""
    tf = "InpTimeframe"
    sym = "InpSymbol"

    if ind_name == "RSI":
        return [
            f"   {handle_var} = iRSI({sym}, {tf}, {prefix}Period, PRICE_CLOSE);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create RSI handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name == "MACD":
        return [
            f"   {handle_var} = iMACD({sym}, {tf}, {prefix}FastEMA, {prefix}SlowEMA, {prefix}Signal, PRICE_CLOSE);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create MACD handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name == "EMA":
        return [
            f"   {handle_var} = iMA({sym}, {tf}, {prefix}Period, 0, MODE_EMA, PRICE_CLOSE);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create EMA handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name == "SMA":
        return [
            f"   {handle_var} = iMA({sym}, {tf}, {prefix}Period, 0, MODE_SMA, PRICE_CLOSE);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create SMA handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name in ("BOLLINGER", "BB"):
        return [
            f"   {handle_var} = iBands({sym}, {tf}, {prefix}Period, 0, {prefix}StdDev, PRICE_CLOSE);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create Bollinger Bands handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name == "ATR":
        return [
            f"   {handle_var} = iATR({sym}, {tf}, {prefix}Period);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create ATR handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name == "STOCHASTIC":
        return [
            f"   {handle_var} = iStochastic({sym}, {tf}, {prefix}KPeriod, {prefix}DPeriod, {prefix}Slowing, MODE_SMA, STO_LOWHIGH);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create Stochastic handle\"); return(INIT_FAILED); }}",
        ]
    elif ind_name == "CCI":
        return [
            f"   {handle_var} = iCCI({sym}, {tf}, {prefix}Period, PRICE_TYPICAL);",
            f"   if({handle_var} == INVALID_HANDLE) {{ Print(\"Failed to create CCI handle\"); return(INIT_FAILED); }}",
        ]
    else:
        return [f"   // TODO: initialise handle for {ind_name}"]


def _build_on_deinit(indicators: list[dict]) -> str:
    lines = [
        "//+------------------------------------------------------------------+",
        "void OnDeinit(const int reason)",
        "{",
    ]
    for ind in indicators:
        lines.append(f"   IndicatorRelease({ind['handle_var']});")
    lines += ["}", ""]
    return "\n".join(lines)


def _build_on_tick(
    direction: str,
    entry_conditions: list[dict],
    exit_conditions: list[dict],
    indicators: list[dict],
    session_filter: list,
) -> str:
    has_atr = any(i["name"].upper() == "ATR" for i in indicators)
    atr_handle = next((i["handle_var"] for i in indicators if i["name"].upper() == "ATR"), None)

    lines = [
        "//+------------------------------------------------------------------+",
        "void OnTick()",
        "{",
        "   // Only act on new bar open",
        "   if(!IsNewBar()) return;",
        "",
    ]

    # Session filter
    if session_filter:
        lines += [
            "   // Session filter",
            "   if(!IsInSession(InpSessions)) return;",
            "",
        ]

    # Daily drawdown check
    lines += [
        "   // Daily drawdown check",
        "   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);",
        "   double equity    = AccountInfoDouble(ACCOUNT_EQUITY);",
        "   if(g_daily_start_balance > 0)",
        "   {",
        "      double dd_pct = (g_daily_start_balance - balance) / g_daily_start_balance * 100.0;",
        "      if(dd_pct >= InpMaxDailyDrawdown)",
        "      {",
        "         Print(\"Daily drawdown limit reached: \", DoubleToString(dd_pct,2), \"%\");",
        "         return;",
        "      }",
        "   }",
        "",
    ]

    # Copy indicator buffers
    lines.append("   // Copy indicator buffers")
    for ind in indicators:
        buffers = ind.get("buffer_vars", [])
        handle_var = ind["handle_var"]
        for i, buf in enumerate(buffers):
            lines.append(f"   if(CopyBuffer({handle_var}, {i}, 0, 3, {buf}) <= 0) return;")
    lines.append("")

    # Entry logic
    lines += [
        "   // ── Entry Logic ──",
        "   if(!g_position_open)",
        "   {",
        "      bool entry_long  = false;",
        "      bool entry_short = false;",
        "",
    ]

    # Build entry condition code
    entry_long_conds, entry_short_conds = _build_condition_code(entry_conditions, indicators, direction)

    if direction in ("LONG", "BOTH"):
        lines.append("      // Long entry conditions")
        lines.append("      entry_long = (" + " &&\n                   ".join(entry_long_conds or ["false"]) + ");")
        lines.append("")

    if direction in ("SHORT", "BOTH"):
        lines.append("      // Short entry conditions")
        lines.append("      entry_short = (" + " &&\n                    ".join(entry_short_conds or ["false"]) + ");")
        lines.append("")

    # ATR-based SL/TP
    if has_atr:
        lines += [
            "      // Calculate SL and TP using ATR",
            f"      double atr_val = {atr_handle == None and '0.001' or ('(' + atr_handle + '_buf[1] > 0 ? ' + atr_handle + '_buf[1] : 0.001)')};",
        ]
    else:
        lines += [
            "      // Fallback fixed SL/TP (20 pips)",
            "      double atr_val = 20 * _Point * 10;",
        ]

    atr_buf_expr = f"(atr_handle_buf[1] > 0 ? atr_handle_buf[1] : 0.001)"
    if has_atr:
        atr_buf = next((i["buffer_vars"][0] for i in indicators if i["name"].upper() == "ATR"), "atr_buf")
        atr_buf_expr = f"({atr_buf}[1] > 0 ? {atr_buf}[1] : 0.001)"

    lines += [
        f"      double sl_dist  = atr_val * InpStopLossATRMult;",
        f"      double tp_dist  = atr_val * InpTakeProfitATRMult;",
        "      double ask      = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);",
        "      double bid      = SymbolInfoDouble(InpSymbol, SYMBOL_BID);",
        "",
    ]

    if direction in ("LONG", "BOTH"):
        lines += [
            "      if(entry_long)",
            "      {",
            "         double sl = ask - sl_dist;",
            "         double tp = ask + tp_dist;",
            "         double lot = CalcLotSize(balance, InpRiskPerTrade, ask, sl);",
            "         if(g_trade.Buy(lot, InpSymbol, ask, sl, tp, \"AlgoForge Long\"))",
            "         {",
            "            g_position_open = true;",
            "            g_entry_price   = ask;",
            "            g_stop_loss     = sl;",
            "            g_take_profit   = tp;",
            "            g_position_dir  = 1;",
            "            Print(\"LONG opened @ \", ask, \" SL:\", sl, \" TP:\", tp);",
            "         }",
            "      }",
        ]

    if direction in ("SHORT", "BOTH"):
        lines += [
            "      else if(entry_short)",
            "      {",
            "         double sl = bid + sl_dist;",
            "         double tp = bid - tp_dist;",
            "         double lot = CalcLotSize(balance, InpRiskPerTrade, bid, sl);",
            "         if(g_trade.Sell(lot, InpSymbol, bid, sl, tp, \"AlgoForge Short\"))",
            "         {",
            "            g_position_open = true;",
            "            g_entry_price   = bid;",
            "            g_stop_loss     = sl;",
            "            g_take_profit   = tp;",
            "            g_position_dir  = -1;",
            "            Print(\"SHORT opened @ \", bid, \" SL:\", sl, \" TP:\", tp);",
            "         }",
            "      }",
        ]

    lines += ["   }", ""]

    # Exit logic
    lines += [
        "   // ── Exit Logic ──",
        "   else",
        "   {",
        "      bool should_exit = false;",
        "",
    ]

    exit_conds = _build_exit_condition_code(exit_conditions, indicators)
    lines.append("      should_exit = (" + " ||\n                    ".join(exit_conds or ["false"]) + ");")
    lines += [
        "",
        "      if(should_exit)",
        "      {",
        "         g_trade.PositionClose(InpSymbol);",
        "         g_position_open = false;",
        "         Print(\"Position closed by signal\");",
        "      }",
        "   }",
        "}",
        "",
    ]
    return "\n".join(lines)


def _build_helpers() -> str:
    return textwrap.dedent("""\
        //+------------------------------------------------------------------+
        //| Helper: detect new bar                                             |
        //+------------------------------------------------------------------+
        bool IsNewBar()
        {
           static datetime last_bar_time = 0;
           datetime current_bar_time = (datetime)SeriesInfoInteger(InpSymbol, InpTimeframe, SERIES_LASTBAR_DATE);
           if(current_bar_time != last_bar_time)
           {
              last_bar_time = current_bar_time;
              return(true);
           }
           return(false);
        }

        //+------------------------------------------------------------------+
        //| Helper: check if current time is within a named session            |
        //+------------------------------------------------------------------+
        bool IsInSession(string sessions)
        {
           if(StringLen(sessions) == 0) return(true);
           MqlDateTime dt;
           TimeToStruct(TimeCurrent(), dt);
           int hour = dt.hour;

           // Session hour ranges (UTC)
           if(StringFind(sessions, "Sydney") >= 0)
              if(hour >= 21 || hour < 6) return(true);
           if(StringFind(sessions, "Tokyo") >= 0)
              if(hour >= 0 && hour < 9) return(true);
           if(StringFind(sessions, "London") >= 0)
              if(hour >= 7 && hour < 16) return(true);
           if(StringFind(sessions, "NewYork") >= 0)
              if(hour >= 12 && hour < 21) return(true);

           return(false);
        }

        //+------------------------------------------------------------------+
        //| Helper: pip value                                                  |
        //+------------------------------------------------------------------+
        double GetPipValue()
        {
           return(_Point * 10);  // 5-digit broker
        }

        //+------------------------------------------------------------------+
        //| Helper: calculate lot size based on risk percentage                |
        //+------------------------------------------------------------------+
        double CalcLotSize(double balance, double risk_pct, double entry, double sl)
        {
           if(sl == 0.0 || entry == 0.0) return(0.01);
           double risk_amount = balance * (risk_pct / 100.0);
           double sl_distance = MathAbs(entry - sl);
           if(sl_distance == 0) return(0.01);
           double pip_size  = GetPipValue();
           double sl_pips   = sl_distance / pip_size;
           if(sl_pips == 0) return(0.01);
           double pip_value = 10.0;  // USD per pip per std lot (approximate)
           double lot = risk_amount / (sl_pips * pip_value);
           double min_lot  = SymbolInfoDouble(InpSymbol, SYMBOL_VOLUME_MIN);
           double max_lot  = SymbolInfoDouble(InpSymbol, SYMBOL_VOLUME_MAX);
           double step     = SymbolInfoDouble(InpSymbol, SYMBOL_VOLUME_STEP);
           lot = MathFloor(lot / step) * step;
           lot = MathMax(min_lot, MathMin(max_lot, lot));
           return(NormalizeDouble(lot, 2));
        }
    """)


# ──────────────────────────────────────────────
# Internal helpers
# ──────────────────────────────────────────────

def _collect_indicators(conditions: list[dict]) -> list[dict]:
    """
    Extract unique indicator definitions from condition list.
    Returns list of dicts with keys: name, params, handle_var, input_prefix, buffer_vars.
    """
    seen: set[str] = set()
    result: list[dict] = []

    for cond in conditions:
        for key in ("indicator", "target"):
            ind_name = cond.get(key, "")
            if not ind_name:
                continue
            params = cond.get("params", {}) if key == "indicator" else cond.get("target_params", {})
            canonical = _canonical_key(ind_name, params)
            if canonical in seen:
                continue
            seen.add(canonical)

            ind_upper = ind_name.upper()
            suffix = _param_suffix(params)
            safe_name = ind_upper.replace(" ", "_").replace("%", "")
            handle_var = f"h_{safe_name}{suffix}"
            input_prefix = f"Inp{safe_name.title().replace('_', '')}{suffix}_"
            buffer_vars = _indicator_buffers(ind_upper, handle_var)

            result.append({
                "name": ind_name,
                "params": params,
                "handle_var": handle_var,
                "input_prefix": input_prefix,
                "buffer_vars": buffer_vars,
            })

    return result


def _canonical_key(name: str, params: dict) -> str:
    param_str = "_".join(f"{k}={v}" for k, v in sorted(params.items()))
    return f"{name.upper()}_{param_str}"


def _param_suffix(params: dict) -> str:
    if not params:
        return ""
    return "_" + "_".join(str(v) for v in params.values())


def _indicator_buffers(ind_upper: str, handle_var: str) -> list[str]:
    """Return buffer variable names for each indicator type."""
    base = handle_var.replace("h_", "") + "_buf"
    if ind_upper == "MACD":
        return [f"{base}_macd", f"{base}_signal", f"{base}_hist"]
    elif ind_upper in ("BOLLINGER", "BB"):
        return [f"{base}_upper", f"{base}_middle", f"{base}_lower"]
    elif ind_upper == "STOCHASTIC":
        return [f"{base}_k", f"{base}_d"]
    else:
        return [base]


def _tf_to_mql5(tf: str) -> str:
    mapping = {
        "M1": "PERIOD_M1", "M5": "PERIOD_M5", "M15": "PERIOD_M15",
        "M30": "PERIOD_M30", "H1": "PERIOD_H1", "H4": "PERIOD_H4",
        "D1": "PERIOD_D1", "W1": "PERIOD_W1", "MN1": "PERIOD_MN1",
    }
    return mapping.get(tf.upper(), "PERIOD_H1")


def _sessions_to_string(session_filter: list) -> str:
    if not session_filter:
        return ""
    return ",".join(str(s) for s in session_filter)


def _build_condition_code(
    conditions: list[dict],
    indicators: list[dict],
    direction: str,
) -> tuple[list[str], list[str]]:
    """
    Convert condition dicts into MQL5 boolean expression strings.
    Returns (long_conds, short_conds).
    """
    long_conds: list[str] = []
    short_conds: list[str] = []

    for cond in conditions:
        ind_name = cond.get("indicator", "").upper()
        params = cond.get("params", {})
        operator = cond.get("operator", "")
        value = cond.get("value")
        target = cond.get("target", "").upper()
        target_params = cond.get("target_params", {})

        # Find matching indicator
        ind_info = _find_indicator(indicators, ind_name, params)
        if not ind_info:
            continue

        buf = ind_info["buffer_vars"][0] if ind_info["buffer_vars"] else "unknown_buf"
        current = f"{buf}[0]"
        prev = f"{buf}[1]"

        expr_long = ""
        expr_short = ""

        if operator == "LESS_THAN" and value is not None:
            expr_long = f"{current} < {value}"
            expr_short = f"{current} > {value}"
        elif operator == "GREATER_THAN" and value is not None:
            expr_long = f"{current} > {value}"
            expr_short = f"{current} < {value}"
        elif operator == "CROSS_ABOVE":
            if target:
                target_info = _find_indicator(indicators, target, target_params)
                if target_info:
                    tbuf = target_info["buffer_vars"][0]
                    expr_long = f"({prev} <= {tbuf}[1] && {current} > {tbuf}[0])"
                    expr_short = f"({prev} >= {tbuf}[1] && {current} < {tbuf}[0])"
            elif value is not None:
                expr_long = f"({prev} <= {value} && {current} > {value})"
                expr_short = f"({prev} >= {value} && {current} < {value})"
        elif operator == "CROSS_BELOW":
            if target:
                target_info = _find_indicator(indicators, target, target_params)
                if target_info:
                    tbuf = target_info["buffer_vars"][0]
                    expr_long = f"({prev} >= {tbuf}[1] && {current} < {tbuf}[0])"
                    expr_short = f"({prev} <= {tbuf}[1] && {current} > {tbuf}[0])"
            elif value is not None:
                expr_long = f"({prev} >= {value} && {current} < {value})"
                expr_short = f"({prev} <= {value} && {current} > {value})"
        elif operator == "BETWEEN" and isinstance(value, (list, tuple)) and len(value) >= 2:
            expr_long = f"({current} >= {value[0]} && {current} <= {value[1]})"
            expr_short = expr_long
        elif operator == "EQUALS" and value is not None:
            expr_long = f"(MathAbs({current} - {value}) < 1e-9)"
            expr_short = expr_long

        if expr_long:
            long_conds.append(expr_long)
        if expr_short:
            short_conds.append(expr_short)

    return long_conds or ["false"], short_conds or ["false"]


def _build_exit_condition_code(
    conditions: list[dict],
    indicators: list[dict],
) -> list[str]:
    """Convert exit condition dicts to MQL5 boolean expressions."""
    exit_conds: list[str] = []

    for cond in conditions:
        ind_name = cond.get("indicator", "").upper()
        params = cond.get("params", {})
        operator = cond.get("operator", "")
        value = cond.get("value")
        target = cond.get("target", "").upper()
        target_params = cond.get("target_params", {})

        ind_info = _find_indicator(indicators, ind_name, params)
        if not ind_info:
            continue

        buf = ind_info["buffer_vars"][0] if ind_info["buffer_vars"] else "unknown_buf"
        current = f"{buf}[0]"
        prev = f"{buf}[1]"

        expr = ""
        if operator == "GREATER_THAN" and value is not None:
            expr = f"{current} > {value}"
        elif operator == "LESS_THAN" and value is not None:
            expr = f"{current} < {value}"
        elif operator == "CROSS_ABOVE":
            if value is not None:
                expr = f"({prev} <= {value} && {current} > {value})"
        elif operator == "CROSS_BELOW":
            if value is not None:
                expr = f"({prev} >= {value} && {current} < {value})"
        elif operator == "BETWEEN" and isinstance(value, (list, tuple)) and len(value) >= 2:
            expr = f"({current} >= {value[0]} && {current} <= {value[1]})"

        if expr:
            logic = cond.get("logic", "AND").upper()
            exit_conds.append(expr)

    return exit_conds or ["false"]


def _find_indicator(indicators: list[dict], name: str, params: dict) -> dict | None:
    for ind in indicators:
        if ind["name"].upper() == name.upper() and ind.get("params", {}) == params:
            return ind
    # Fallback: match by name only
    for ind in indicators:
        if ind["name"].upper() == name.upper():
            return ind
    return None
